import type { Metadata } from "next";
import "@/styles/globals.css";
import { FloatingMenu } from "@/components/floating-menu";
import { Footer } from "@/components/footer";
import { routing } from "@/i18n/routing";
import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { Toaster } from "sonner";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function MainLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;
	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	return (
		<>
			<Toaster />
			<div className="max-w-3xl mx-auto relative px-4 md:px-6">
				<div className="absolute inset-x-4 md:inset-x-6 top-0 bottom-0 border-x border-dashed pointer-events-none" />
				<div className="flex flex-col min-h-dvh">
					<div className="p-4 md:p-6 flex-grow">{children}</div>
					<Footer />
				</div>
				<FloatingMenu />
			</div>
		</>
	);
}
