import type { Metadata } from "next";
import "@/styles/globals.css";
import { FloatingMenu } from "@/components/floating-menu";
import { Footer } from "@/components/footer";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	params,
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;
	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}

	return (
		<html lang={locale} suppressHydrationWarning>
			<head />
			<body>
				<NextIntlClientProvider>
					<ThemeProvider
						attribute="class"
						defaultTheme="system"
						enableSystem
						disableTransitionOnChange
					>
						<div className="max-w-4xl mx-auto relative px-6">
							<div className="absolute inset-x-6 top-0 bottom-0 border-x border-dashed pointer-events-none" />
							<div className="flex flex-col min-h-dvh">
								<div className="px-6 pt-12 flex-grow">{children}</div>
								<Footer />
							</div>
							<FloatingMenu />
						</div>
					</ThemeProvider>
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
